function ctx = ml_capture_training_context(p)
%ML_CAPTURE_TRAINING_CONTEXT  提取与符号级脉冲训练直接相关的链路上下文。
arguments
    p (1,1) struct
end

ctx = struct();
ctx.rngSeed = local_get_numeric(p, "rngSeed", NaN);
ctx.mod = struct("type", string(p.mod.type));
ctx.waveform = struct( ...
    "enable", local_get_logical(p.waveform, "enable", false), ...
    "symbolRateHz", local_get_numeric(p.waveform, "symbolRateHz", NaN), ...
    "sps", local_get_numeric(p.waveform, "sps", NaN), ...
    "rolloff", local_get_numeric(p.waveform, "rolloff", NaN), ...
    "spanSymbols", local_get_numeric(p.waveform, "spanSymbols", NaN), ...
    "rxMatchedFilter", local_get_logical(p.waveform, "rxMatchedFilter", false));
ctx.channel = struct( ...
    "impulseProb", local_get_numeric(p.channel, "impulseProb", NaN), ...
    "impulseToBgRatio", local_get_numeric(p.channel, "impulseToBgRatio", NaN), ...
    "multipathEnable", local_get_nested_logical(p.channel, "multipath", "enable", false), ...
    "rayleigh", local_get_nested_logical(p.channel, "multipath", "rayleigh", false), ...
    "singleToneEnable", local_get_nested_logical(p.channel, "singleTone", "enable", false), ...
    "narrowbandEnable", local_get_nested_logical(p.channel, "narrowband", "enable", false), ...
    "sweepEnable", local_get_nested_logical(p.channel, "sweep", "enable", false), ...
    "syncImpairmentEnable", local_get_nested_logical(p.channel, "syncImpairment", "enable", false));
ctx.fh = struct( ...
    "enable", local_get_logical(p.fh, "enable", false), ...
    "nFreqs", local_get_numeric(p.fh, "nFreqs", NaN), ...
    "symbolsPerHop", local_get_numeric(p.fh, "symbolsPerHop", NaN));
ctx.rxSync = struct( ...
    "compensateCarrier", local_get_logical(p.rxSync, "compensateCarrier", false), ...
    "estimateCfo", local_get_logical(p.rxSync, "estimateCfo", false), ...
    "fractionalTiming", local_get_logical(p.rxSync, "enableFractionalTiming", false), ...
    "carrierPllEnable", local_get_nested_logical(p.rxSync, "carrierPll", "enable", false));
end

function value = local_get_numeric(s, fieldName, defaultValue)
if isfield(s, fieldName) && ~isempty(s.(fieldName))
    value = double(s.(fieldName));
else
    value = defaultValue;
end
end

function value = local_get_logical(s, fieldName, defaultValue)
if isfield(s, fieldName) && ~isempty(s.(fieldName))
    value = logical(s.(fieldName));
else
    value = defaultValue;
end
end

function value = local_get_nested_logical(s, parentField, childField, defaultValue)
if isfield(s, parentField) && isstruct(s.(parentField))
    value = local_get_logical(s.(parentField), childField, defaultValue);
else
    value = defaultValue;
end
end
