function profile = ml_default_impulse_offline_training_profile(p)
%ML_DEFAULT_IMPULSE_OFFLINE_TRAINING_PROFILE  Default offline profile for impulse-interference models.

arguments
    p (1,1) struct
end

[centerFreqPointsRange, bandwidthFreqPointsRange] = ...
    local_narrowband_training_ranges(p, [-2500, 2500], [200, 1800]);

profile = struct();
profile.profileName = "impulse_mixed_default_v3";
profile.scenario = struct( ...
    "ebN0dBRange", [-2, 16], ...
    "labelScoreThreshold", 0.1, ...
    "thresholdPolicy", "min_pe_under_pfa", ...
    "minPositiveRate", 0.002, ...
    "maxPositiveRate", 0.30, ...
    "impulseEnableProbability", 0.85, ...
    "impulseProbRange", [0.002, 0.05], ...
    "impulseToBgRatioRange", [10, 80], ...
    "singleToneProbability", 0.35, ...
    "singleTonePowerRange", [0.0025, 0.12], ...
    "singleToneFreqHzRange", [-2500, 2500], ...
    "narrowbandProbability", 0.35, ...
    "narrowbandPowerRange", [0.0025, 0.12], ...
    "narrowbandCenterFreqPointsRange", centerFreqPointsRange, ...
    "narrowbandBandwidthFreqPointsRange", bandwidthFreqPointsRange, ...
    "sweepProbability", 0.20, ...
    "sweepPowerRange", [0.0025, 0.08], ...
    "sweepStartHzRange", [-3500, -500], ...
    "sweepStopHzRange", [500, 3500], ...
    "sweepPeriodSymbolsRange", [64, 512], ...
    "syncImpairmentProbability", 0.15, ...
    "timingOffsetSymbolsRange", [-0.35, 0.35], ...
    "phaseOffsetRadRange", [-pi, pi], ...
    "multipathProbability", 0.20, ...
    "multipathRayleighProbability", 0.50, ...
    "maxAdditionalImpairments", 2);
profile.logisticRegression = struct( ...
    "nBlocks", 1000, ...
    "blockLen", 4096, ...
    "epochs", 100, ...
    "batchSize", 65536, ...
    "lr", 0.2, ...
    "l2", 1e-3);
profile.deepLearning = struct( ...
    "nBlocks", 1000, ...
    "blockLen", 1024, ...
    "epochs", 100, ...
    "batchSize", 64, ...
    "lr", 1e-3);
end

function [centerFreqPointsRange, bandwidthFreqPointsRange] = local_narrowband_training_ranges(p, centerHzRange, bandwidthHzRange)
waveform = resolve_waveform_cfg(p);
spacingHz = fh_frequency_spacing_hz(p.fh, waveform);

centerHzRange = double(centerHzRange(:).');
bandwidthHzRange = double(bandwidthHzRange(:).');
if numel(centerHzRange) ~= 2 || any(~isfinite(centerHzRange)) || centerHzRange(1) > centerHzRange(2)
    error("ml_default_impulse_offline_training_profile:InvalidCenterHzRange", ...
        "centerHzRange must be an ascending finite 1x2 range.");
end
if numel(bandwidthHzRange) ~= 2 || any(~isfinite(bandwidthHzRange)) ...
        || bandwidthHzRange(1) <= 0 || bandwidthHzRange(1) > bandwidthHzRange(2)
    error("ml_default_impulse_offline_training_profile:InvalidBandwidthHzRange", ...
        "bandwidthHzRange must be a positive ascending finite 1x2 range.");
end

bandwidthFreqPointsRange = bandwidthHzRange / spacingHz;
bandwidthFreqPointsRange = max(bandwidthFreqPointsRange, 1e-6);
[maxCenterFreqPoints, ~] = narrowband_center_freq_points_limit(p.fh, waveform, bandwidthFreqPointsRange(2));
centerFreqPointsRange = centerHzRange / spacingHz;
centerFreqPointsRange = max(min(centerFreqPointsRange, maxCenterFreqPoints), -maxCenterFreqPoints);
centerFreqPointsRange = sort(centerFreqPointsRange);
end
