function names = ml_fh_erasure_feature_names()
%ML_FH_ERASURE_FEATURE_NAMES  Canonical per-hop feature order for FH erasure.

names = [ ...
    "hopPowerRatio", ...
    "hopAbsMeanRatio", ...
    "hopAbsStdRatio", ...
    "freqMedianPowerRatio", ...
    "freqMeanPowerRatio", ...
    "freqMaxPowerRatio", ...
    "prevHopPowerRatio", ...
    "nextHopPowerRatio", ...
    "hopToFreqPowerRatio", ...
    "freqHotFraction", ...
    "freqIndexNorm", ...
    "absFreqOffsetNorm", ...
    "hopIndexNorm", ...
    "constellationMse", ...
    "iqPowerImbalance", ...
    "edgeHop", ...
    "ruleFreqReliability", ...
    "ruleHopReliability", ...
    "ruleReliability"];
end
