function names = ml_fh_erasure_freq_feature_names()
%ML_FH_ERASURE_FREQ_FEATURE_NAMES  Canonical per-frequency feature order.

names = [ ...
    "freqHopPowerMedian", ...
    "freqHopPowerMean", ...
    "freqHopPowerMax", ...
    "freqHopPowerP90", ...
    "freqAbsMeanMedian", ...
    "freqAbsStdMedian", ...
    "freqMedianPowerRatio", ...
    "freqMeanPowerRatio", ...
    "freqMaxPowerRatio", ...
    "freqHotFraction", ...
    "freqHopToFreqMedian", ...
    "freqConstellationMseMedian", ...
    "freqConstellationMseP90", ...
    "freqIqImbalanceMedian", ...
    "freqIqImbalanceP90", ...
    "freqIndexNorm", ...
    "absFreqOffsetNorm", ...
    "freqHopCoverage", ...
    "freqEdgeFraction", ...
    "ruleFreqReliability", ...
    "ruleHopReliabilityMin", ...
    "ruleReliabilityMin"];
end
