function names = ml_interference_selector_feature_names()
%ML_INTERFERENCE_SELECTOR_FEATURE_NAMES  Canonical feature order for the interference selector.

names = [ ...
    "preResidualEnergy", ...
    "preResidualPeakRatio", ...
    "preResidualKurtosis", ...
    "preResidualOutlierRate", ...
    "fftPeakRatio", ...
    "fftBandOccupancy", ...
    "fftDominantBandwidth", ...
    "stftDominantDrift", ...
    "channelTailEnergyRatio", ...
    "channelDelaySpread", ...
    "cfoAbs", ...
    "gainAbsError", ...
    "corrPeakToMedian", ...
    "corrPeakToSecond"];
end
