function names = ml_narrowband_feature_names()
%ML_NARROWBAND_FEATURE_NAMES  Canonical feature order for narrowband action prediction.

names = [ ...
    "fftPeakRatio", ...
    "fftBandOccupancy", ...
    "fftDominantBandwidth", ...
    "stftDominantDrift", ...
    "spectralFlatness", ...
    "ampKurtosis", ...
    "ampOutlierRate", ...
    "probeApplied", ...
    "probePeakRatio", ...
    "probeBandwidthFrac", ...
    "probeCenterFreqAbs", ...
    "probeMaskFraction"];
end
