function summary = search_robust_unified_all_three_light(opts)
%SEARCH_ROBUST_UNIFIED_ALL_THREE_LIGHT Find a lighter robust_unified point that still passes all_three.

arguments
    opts.EbN0dB (1,1) double {mustBeFinite} = 6
    opts.JsrDb (1,1) double {mustBeFinite} = 0
    opts.BurstThresholdSec (1,1) double {mustBePositive} = 60
    opts.ElapsedThresholdSec (1,1) double {mustBePositive} = 1200
    opts.ResultsRoot (1,1) string = fullfile("results", "search_robust_unified_all_three_light")
    opts.Tag (1,1) string = "all_three_256sq"
    opts.CandidateNames (1,:) string = strings(1, 0)
    opts.StopOnFirstFailureAfterPass (1,1) logical = true
    opts.SaveFullResults (1,1) logical = false
end

addpath(genpath("src"));

candidates = local_candidate_table();
if ~isempty(opts.CandidateNames)
    mask = ismember(string({candidates.name}), string(opts.CandidateNames));
    if ~any(mask)
        error("No candidate names matched the requested CandidateNames list.");
    end
    candidates = candidates(mask);
end
timestamp = string(datetime("now", "Format", "yyyyMMdd_HHmmss"));
outRoot = fullfile(opts.ResultsRoot, opts.Tag + "_" + timestamp);
if ~exist(char(outRoot), "dir")
    mkdir(char(outRoot));
end

rows = repmat(local_empty_row(), numel(candidates), 1);
seenPass = false;

for idx = 1:numel(candidates)
    cand = candidates(idx);
    row = local_empty_row();
    row.index = idx;
    row.name = cand.name;
    row.runDir = string(fullfile(outRoot, char(cand.name)));
    if ~exist(char(row.runDir), "dir")
        mkdir(char(row.runDir));
    end

    try
        spec = default_link_spec( ...
            "linkProfileName", "robust_unified", ...
            "loadMlModels", string.empty(1, 0), ...
            "strictModelLoad", false, ...
            "requireTrainedMlModels", false);
        spec.sim.nFramesPerPoint = 1;
        spec.sim.useParallel = false;
        spec.sim.saveFigures = false;
        spec.sim.resultsDir = char(row.runDir);
        spec.linkBudget.ebN0dBList = double(opts.EbN0dB);
        spec.linkBudget.jsrDbList = double(opts.JsrDb);
        spec = local_apply_all_three_case(spec);
        spec = local_apply_candidate(spec, cand);

        validate_link_profile(spec);

        tStart = tic;
        results = run_link_profile(spec);
        elapsedSec = toc(tStart);

        row.runOk = true;
        row.burstSec = double(results.tx.burstDurationSec);
        row.elapsedSec = elapsedSec;
        row.method = string(results.methods(1));
        row.ber = double(results.ber(1, 1));
        row.rawPer = double(results.rawPer(1, 1));
        row.per = double(results.per(1, 1));
        row.perExact = double(results.perExact(1, 1));
        row.frontEndSuccess = double(results.packetDiagnostics.bob.frontEndSuccessRateByMethod(1, 1));
        row.headerSuccess = double(results.packetDiagnostics.bob.headerSuccessRateByMethod(1, 1));
        row.sessionSuccess = double(results.packetDiagnostics.bob.sessionSuccessRateByMethod(1, 1));
        row.payloadSuccess = double(results.packetDiagnostics.bob.payloadSuccessRate(1, 1));
        row.pass = row.per == 0 ...
            && row.burstSec < double(opts.BurstThresholdSec) ...
            && row.elapsedSec < double(opts.ElapsedThresholdSec);
        row.passPerOnly = row.per == 0 && row.burstSec < double(opts.BurstThresholdSec);

        local_save_case_result(row.runDir, row, cand, spec, results, elapsedSec, opts.SaveFullResults);
    catch ME
        row.runOk = false;
        row.errorMessage = string(ME.message);
    end

    rows(idx) = row;
    fprintf("[RU-LIGHT] %s runOk=%d pass=%d passPerOnly=%d PER=%.4g rawPER=%.4g burst=%.3fs elapsed=%.3fs\n", ...
        char(row.name), row.runOk, row.pass, row.passPerOnly, row.per, row.rawPer, row.burstSec, row.elapsedSec);
    if strlength(row.errorMessage) > 0
        fprintf("[RU-LIGHT]   error: %s\n", row.errorMessage);
    end

    if row.runOk && row.passPerOnly
        seenPass = true;
    elseif seenPass && opts.StopOnFirstFailureAfterPass
        rows = rows(1:idx);
        break;
    end
end

summary = struct2table(rows);
writetable(summary, fullfile(outRoot, "summary.csv"));
save(fullfile(outRoot, "summary.mat"), "summary");
fprintf("[RU-LIGHT] summary: %s\n", fullfile(outRoot, "summary.csv"));
end

function spec = local_apply_all_three_case(spec)
spec.channel.impulseProb = 0.03;
spec.channel.impulseWeight = 1.0;
spec.channel.impulseToBgRatio = 0.0;
spec.channel.narrowband.enable = true;
spec.channel.narrowband.weight = 1.0;
spec.channel.narrowband.centerFreqPoints = 0;
spec.channel.narrowband.bandwidthFreqPoints = local_robust_unified_narrowband_bandwidth(spec);
spec.channel.multipath.enable = true;
spec.channel.multipath.pathDelaysSymbols = [0 2 4];
spec.channel.multipath.pathGainsDb = [0 -6 -10];
spec.channel.multipath.rayleigh = true;
end

function bw = local_robust_unified_narrowband_bandwidth(spec)
runtimeCfg = compile_runtime_config(spec);
bw = narrowband_prespread_fh_bandwidth_points(runtimeCfg.fh, runtimeCfg.waveform, runtimeCfg.dsss);
end

function spec = local_apply_candidate(spec, cand)
controlPlan = guarded_control_freq_plan(spec.profileTx.cfg.fh.freqSet);
controlFreqSet = local_pick_control_freq_set(controlPlan.controlOnlyFreqSet, cand.controlCopies);

spec.commonTx.control.sessionHeaderMode = "session_frame_repeat";
spec.commonTx.control.sessionFrameRepeatCount = cand.sessionFrameRepeatCount;
spec.commonTx.control.phyHeaderRepeatCompact = cand.phyHeaderRepeatCompact;
spec.commonTx.control.phyHeaderSpreadFactor = cand.phyHeaderSpreadFactor;
spec.commonTx.control.preambleDiversity.enable = cand.controlCopies > 1;
spec.commonTx.control.preambleDiversity.copies = cand.controlCopies;
spec.commonTx.control.preambleDiversity.freqSet = controlFreqSet;
spec.commonTx.control.sessionHeaderBodyDiversity.enable = cand.controlCopies > 1;
spec.commonTx.control.sessionHeaderBodyDiversity.copies = cand.controlCopies;
spec.commonTx.control.sessionHeaderBodyDiversity.freqSet = controlFreqSet;
spec.commonTx.control.phyHeaderDiversity.enable = cand.controlCopies > 1;
spec.commonTx.control.phyHeaderDiversity.copies = cand.controlCopies;
spec.commonTx.control.phyHeaderFhFreqSet = controlPlan.controlOnlyFreqSet;

spec.commonTx.innerCode.ldpc.maxIterations = cand.ldpcMaxIterations;
spec.commonTx.interleaver.nRows = cand.interleaverRows;
spec.commonTx.outerRs.dataPacketsPerBlock = cand.rsDataPacketsPerBlock;
spec.commonTx.outerRs.parityPacketsPerBlock = cand.rsParityPacketsPerBlock;
end

function freqSet = local_pick_control_freq_set(controlOnlyFreqSet, copies)
controlOnlyFreqSet = double(controlOnlyFreqSet(:).');
if copies <= 1
    freqSet = controlOnlyFreqSet(1);
    return;
end
if copies == 3
    idx = [1 ceil(numel(controlOnlyFreqSet) / 2) numel(controlOnlyFreqSet)];
else
    idx = round(linspace(1, numel(controlOnlyFreqSet), copies));
end
idx = unique(max(1, min(numel(controlOnlyFreqSet), idx)), "stable");
if numel(idx) ~= copies
    error("Could not select %d distinct control frequencies from %d tones.", copies, numel(controlOnlyFreqSet));
end
freqSet = controlOnlyFreqSet(idx);
end

function candidates = local_candidate_table()
candidates = [
    struct( ...
        "name", "c1_rs4p6_ctrl4_ldpc12_int256", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 6, ...
        "sessionFrameRepeatCount", 4, ...
        "controlCopies", 4, ...
        "phyHeaderRepeatCompact", 5, ...
        "phyHeaderSpreadFactor", 8, ...
        "ldpcMaxIterations", 12, ...
        "interleaverRows", 256)
    struct( ...
        "name", "c2_rs4p4_ctrl4_ldpc12_int256", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 4, ...
        "sessionFrameRepeatCount", 4, ...
        "controlCopies", 4, ...
        "phyHeaderRepeatCompact", 5, ...
        "phyHeaderSpreadFactor", 8, ...
        "ldpcMaxIterations", 12, ...
        "interleaverRows", 256)
    struct( ...
        "name", "c3_rs4p4_ctrl4_ldpc10_int128", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 4, ...
        "sessionFrameRepeatCount", 4, ...
        "controlCopies", 4, ...
        "phyHeaderRepeatCompact", 5, ...
        "phyHeaderSpreadFactor", 8, ...
        "ldpcMaxIterations", 10, ...
        "interleaverRows", 128)
    struct( ...
        "name", "c4_rs4p4_ctrl3_ldpc10_int128", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 4, ...
        "sessionFrameRepeatCount", 3, ...
        "controlCopies", 3, ...
        "phyHeaderRepeatCompact", 4, ...
        "phyHeaderSpreadFactor", 6, ...
        "ldpcMaxIterations", 10, ...
        "interleaverRows", 128)
    struct( ...
        "name", "c5_rs4p4_ctrl3_sess2_ldpc10_int128", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 4, ...
        "sessionFrameRepeatCount", 2, ...
        "controlCopies", 3, ...
        "phyHeaderRepeatCompact", 4, ...
        "phyHeaderSpreadFactor", 6, ...
        "ldpcMaxIterations", 10, ...
        "interleaverRows", 128)
    struct( ...
        "name", "c6_rs4p4_ctrl2_sess2_ldpc10_int128", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 4, ...
        "sessionFrameRepeatCount", 2, ...
        "controlCopies", 2, ...
        "phyHeaderRepeatCompact", 4, ...
        "phyHeaderSpreadFactor", 4, ...
        "ldpcMaxIterations", 10, ...
        "interleaverRows", 128)
    struct( ...
        "name", "c7_rs4p4_ctrl2_sess2_ldpc10_int128_legacyhdr", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 4, ...
        "sessionFrameRepeatCount", 2, ...
        "controlCopies", 2, ...
        "phyHeaderRepeatCompact", 3, ...
        "phyHeaderSpreadFactor", 4, ...
        "ldpcMaxIterations", 10, ...
        "interleaverRows", 128)
    struct( ...
        "name", "c8_rs4p2_ctrl2_sess2_ldpc10_int128_legacyhdr", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 2, ...
        "sessionFrameRepeatCount", 2, ...
        "controlCopies", 2, ...
        "phyHeaderRepeatCompact", 3, ...
        "phyHeaderSpreadFactor", 4, ...
        "ldpcMaxIterations", 10, ...
        "interleaverRows", 128)
    struct( ...
        "name", "c9_rs4p2_ctrl2_sess2_ldpc8_int64_legacyhdr", ...
        "rsDataPacketsPerBlock", 4, ...
        "rsParityPacketsPerBlock", 2, ...
        "sessionFrameRepeatCount", 2, ...
        "controlCopies", 2, ...
        "phyHeaderRepeatCompact", 3, ...
        "phyHeaderSpreadFactor", 4, ...
        "ldpcMaxIterations", 8, ...
        "interleaverRows", 64)
    ];
end

function local_save_case_result(runDir, row, cand, spec, results, elapsedSec, saveFullResults)
caseResult = struct();
caseResult.row = row;
caseResult.candidate = cand;
caseResult.txSummary = struct("burstDurationSec", double(results.tx.burstDurationSec));
caseResult.elapsedSec = elapsedSec;
if saveFullResults
    save(fullfile(runDir, "case_result.mat"), "caseResult", "cand", "spec", "results", "elapsedSec", "-v7.3");
else
    save(fullfile(runDir, "case_result.mat"), "caseResult", "cand", "spec");
end
end

function row = local_empty_row()
row = struct( ...
    "index", NaN, ...
    "name", "", ...
    "method", "", ...
    "runOk", false, ...
    "pass", false, ...
    "passPerOnly", false, ...
    "burstSec", NaN, ...
    "elapsedSec", NaN, ...
    "ber", NaN, ...
    "rawPer", NaN, ...
    "per", NaN, ...
    "perExact", NaN, ...
    "frontEndSuccess", NaN, ...
    "headerSuccess", NaN, ...
    "sessionSuccess", NaN, ...
    "payloadSuccess", NaN, ...
    "runDir", "", ...
    "errorMessage", "");
end
