function tmp_validate_robust_unified_probe()
addpath(genpath("src"));
validate_robust_unified_mixed( ...
    "Cases", "narrowband_rayleigh", ...
    "Variants", "baseline", ...
    "Tag", "robust_unified_jointldpc_nb_rayleigh_probe_6db", ...
    "ElapsedThresholdSec", 120, ...
    "BurstThresholdSec", 60);
end
