function tmp_validate_robust_unified_single_rayleigh_sps10()
addpath(genpath("src"));
validate_robust_unified_single_sweeps( ...
    "Suites", "rayleigh_multipath", ...
    "Tag", "robust_unified_single_rayleigh_sps10_sr600k_6db");
end
