function tmp_validate_robust_unified_full()
addpath(genpath("src"));
validate_robust_unified_mixed( ...
    "Cases", ["impulse_narrowband" "impulse_rayleigh" "narrowband_rayleigh" "all_three"], ...
    "Variants", "baseline", ...
    "Tag", "robust_unified_jointldpc_full_6db", ...
    "ElapsedThresholdSec", 120, ...
    "BurstThresholdSec", 60);
end
