function tmp_validate_robust_unified_single()
addpath(genpath("src"));
validate_robust_unified( ...
    "EbN0dB", 6, ...
    "JsrDb", 0, ...
    "NFramesPerPoint", 1, ...
    "BurstThresholdSec", 60, ...
    "ElapsedThresholdSec", 120, ...
    "Tag", "robust_unified_jointldpc_single_6db");
end
