function tmp_validate_robust_unified_single_impulse_sps10()
addpath(genpath("src"));
validate_robust_unified_single_sweeps( ...
    "Suites", "impulse", ...
    "Tag", "robust_unified_single_impulse_sps10_sr600k_6db");
end
