function captureDiag = rx_build_capture_diag(front)
%RX_BUILD_CAPTURE_DIAG Standardize capture diagnostics for packet/session RX.

captureDiag = struct( ...
    "ok", logical(front.ok), ...
    "bootstrapPath", string(front.bootstrapPath), ...
    "startIdx", double(front.startIdx), ...
    "packetStartSample", double(front.packetStartSample), ...
    "packetStopSample", double(front.packetStopSample), ...
    "packetSampleLen", double(front.packetSampleLen), ...
    "syncStageSps", double(front.syncStageSps), ...
    "syncInfo", front.syncInfo);
end
