function [headerBits, header] = build_header_bits(meta, magic16)
%BUILD_HEADER_BITS  Build fixed-length header bitstream.

header = struct();
header.magic = uint16(magic16);
header.rows = meta.rows;
header.cols = meta.cols;
header.channels = meta.channels;
header.bitsPerPixel = meta.bitsPerPixel;
header.payloadBytes = meta.payloadBytes;

fields = [ ...
    uint16_to_bits(header.magic); ...
    uint16_to_bits(header.rows); ...
    uint16_to_bits(header.cols); ...
    uint8_scalar_to_bits(header.channels); ...
    uint8_scalar_to_bits(header.bitsPerPixel); ...
    uint32_to_bits(header.payloadBytes) ...
    ];
headerBits = uint8(fields);
end

