function txArtifacts = build_tx_artifacts(linkSpec, runtimeCfg)
%BUILD_TX_ARTIFACTS Build standardized transmitter artifacts for the active profile.

arguments
    linkSpec (1,1) struct
    runtimeCfg struct = struct()
end

if isempty(fieldnames(runtimeCfg))
    runtimeCfg = compile_runtime_config(linkSpec);
end

waveform = resolve_waveform_cfg(runtimeCfg);
[imgTx, imgOriginal] = load_source_image(runtimeCfg.source);
payloadCodec = get_payload_codec(runtimeCfg.payload);
usePayloadBitChaos = payloadCodec ~= "raw";
packetIndependentBitChaos = false;

chaosEnabled = isfield(runtimeCfg, "chaosEncrypt") && isfield(runtimeCfg.chaosEncrypt, "enable") ...
    && logical(runtimeCfg.chaosEncrypt.enable);
imgForPayload = imgTx;
chaosInfo = struct("enabled", false, "mode", "none");
if chaosEnabled && ~usePayloadBitChaos
    [imgForPayload, chaosInfo] = chaos_encrypt(imgTx, runtimeCfg.chaosEncrypt);
    chaosInfo.mode = "image";
end

[payloadBitsPlain, payloadMeta] = image_to_payload_bits(imgForPayload, runtimeCfg.payload);
payloadBitsTx = payloadBitsPlain;
if chaosEnabled && usePayloadBitChaos
    if ~isfield(runtimeCfg.chaosEncrypt, "packetIndependent")
        runtimeCfg.chaosEncrypt.packetIndependent = true;
    end
    packetIndependentBitChaos = logical(runtimeCfg.chaosEncrypt.packetIndependent);
    if packetIndependentBitChaos
        chaosInfo.enabled = true;
        chaosInfo.mode = "payload_bits_packet";
    else
        [payloadBitsTx, chaosInfo] = chaos_encrypt_bits(payloadBitsPlain, runtimeCfg.chaosEncrypt);
    end
end

[txPackets, txPlan] = build_tx_packets(payloadBitsTx, payloadMeta, runtimeCfg, packetIndependentBitChaos, waveform);
burstReport = measure_tx_burst(txPlan.txBurstForChannel, waveform);

packetTable = local_build_packet_table_local(txPackets);
headerAssist = struct( ...
    "frame", runtimeCfg.frame, ...
    "sessionMeta", txPlan.sessionMeta, ...
    "sessionFrames", txPlan.sessionFrames, ...
    "phyHeaderMode", string(runtimeCfg.frame.phyHeaderMode), ...
    "sessionHeaderMode", string(runtimeCfg.frame.sessionHeaderMode));
payloadAssist = struct( ...
    "payloadBitsPlain", payloadBitsPlain, ...
    "payloadBitsTx", payloadBitsTx, ...
    "payloadCodec", string(runtimeCfg.payload.codec), ...
    "payloadMeta", payloadMeta, ...
    "chaosInfo", chaosInfo, ...
    "nDataPackets", double(txPlan.nDataPackets), ...
    "packetIndependentBitChaos", logical(packetIndependentBitChaos));
commonMeta = struct( ...
    "profileName", string(linkSpec.linkProfile.name), ...
    "waveform", waveform, ...
    "modInfo", txPlan.modInfo, ...
    "burstReport", burstReport, ...
    "sourceImage", imgTx, ...
    "sourceImageOriginal", imgOriginal, ...
    "sessionMeta", txPlan.sessionMeta);
profileMeta = struct( ...
    "txMapper", string(linkSpec.linkProfile.txMapper), ...
    "profileTxName", string(linkSpec.profileTx.name), ...
    "fhEnabled", logical(txPlan.fhEnabled), ...
    "dsssEnabled", logical(txPlan.dsssEnable), ...
    "scFdeEnabled", logical(txPlan.scFdeEnable), ...
    "outerRs", txPlan.outerRs, ...
    "sessionFramePlan", txPlan.sessionFramePlan);
packetAssist = struct( ...
    "txPackets", txPackets, ...
    "txPlan", txPlan);

txArtifacts = struct( ...
    "burstForChannel", txPlan.txBurstForChannel, ...
    "packetTable", packetTable, ...
    "headerAssist", headerAssist, ...
    "payloadAssist", payloadAssist, ...
    "commonMeta", commonMeta, ...
    "profileMeta", profileMeta, ...
    "packetAssist", packetAssist);
end

function packetTable = local_build_packet_table_local(txPackets)
nPackets = numel(txPackets);
packetTable = repmat(struct( ...
    "packetIndex", NaN, ...
    "isDataPacket", false, ...
    "isParityPacket", false, ...
    "sourcePacketIndex", NaN, ...
    "blockIndex", NaN, ...
    "blockDataCount", NaN, ...
    "blockParityCount", NaN, ...
    "payloadBytes", NaN, ...
    "packetDataBytes", NaN, ...
    "hasSessionHeader", false, ...
    "nDemodSym", NaN, ...
    "nDataSymTx", NaN, ...
    "nPhyHeaderSymTx", NaN, ...
    "fhEnabled", false, ...
    "scFdeEnabled", false), nPackets, 1);

for pktIdx = 1:nPackets
    pkt = txPackets(pktIdx);
    packetTable(pktIdx).packetIndex = double(pkt.packetIndex);
    packetTable(pktIdx).isDataPacket = logical(pkt.isDataPacket);
    packetTable(pktIdx).isParityPacket = logical(pkt.isParityPacket);
    packetTable(pktIdx).sourcePacketIndex = double(pkt.sourcePacketIndex);
    packetTable(pktIdx).blockIndex = double(pkt.blockIndex);
    packetTable(pktIdx).blockDataCount = double(pkt.blockDataCount);
    packetTable(pktIdx).blockParityCount = double(pkt.blockParityCount);
    packetTable(pktIdx).payloadBytes = double(pkt.payloadBytes);
    packetTable(pktIdx).packetDataBytes = double(pkt.packetDataBytes);
    packetTable(pktIdx).hasSessionHeader = logical(pkt.hasSessionHeader);
    packetTable(pktIdx).nDemodSym = double(pkt.nDemodSym);
    packetTable(pktIdx).nDataSymTx = double(pkt.nDataSymTx);
    packetTable(pktIdx).nPhyHeaderSymTx = double(pkt.nPhyHeaderSymTx);
    packetTable(pktIdx).fhEnabled = isfield(pkt, "fhCfg") && isfield(pkt.fhCfg, "enable") && logical(pkt.fhCfg.enable);
    packetTable(pktIdx).scFdeEnabled = isfield(pkt, "scFdeInfo") && isfield(pkt.scFdeInfo, "enable") && logical(pkt.scFdeInfo.enable);
end
end
