function linkSpec = default_link_spec(opts)
%DEFAULT_LINK_SPEC Build the independent linkSpec for the refactored three-profile architecture.

arguments
    opts.strictModelLoad (1,1) logical = true
    opts.requireTrainedMlModels (1,1) logical = true
    opts.allowBatchModelFallback (1,1) logical = true
    opts.linkProfileName (1,1) string = "narrowband"
    opts.loadMlModels string = ["lr" "cnn" "gru" "selector" "narrowband" "fh_erasure"]
end

profileName = normalize_link_profile_name(opts.linkProfileName);
requestedModels = string(opts.loadMlModels(:).');

commonTx = local_common_tx_defaults_local();
channel = local_channel_defaults_local();
[commonTx, channel, profileTxCfg, profileRxCfg] = local_apply_profile_defaults_local( ...
    commonTx, channel, profileName);

runtime = struct( ...
    "rngSeed", 5489, ...
    "txSkeleton", "common_tx_skeleton_v1", ...
    "captureTxArtifacts", true, ...
    "performance", struct( ...
        "preset", "lean_independent", ...
        "singleFrameTargetSec", 60), ...
    "compileOptions", struct( ...
        "strictModelLoad", logical(opts.strictModelLoad), ...
        "requireTrainedMlModels", logical(opts.requireTrainedMlModels), ...
        "allowBatchModelFallback", logical(opts.allowBatchModelFallback), ...
        "loadMlModels", requestedModels));

linkSpec = struct();
linkSpec.apiVersion = "linkSpec.v1";
linkSpec.linkProfile = struct( ...
    "name", profileName, ...
    "supportedProfiles", ["impulse" "narrowband" "rayleigh_multipath" "robust_unified"], ...
    "txMapper", local_tx_mapper_name_local(profileName), ...
    "rxChain", local_rx_chain_name_local(profileName));
linkSpec.runtime = runtime;
linkSpec.sim = struct( ...
    "nFramesPerPoint", 1, ...
    "saveFigures", false, ...
    "useParallel", false, ...
    "nWorkers", 0, ...
    "resultsDir", "");
linkSpec.linkBudget = struct( ...
    "noisePsdLin", 1.0, ...
    "ebN0dBList", 8, ...
    "jsrDbList", 0);
linkSpec.channel = channel;
linkSpec.commonTx = commonTx;
linkSpec.profileTx = struct( ...
    "name", profileName, ...
    "mapper", local_tx_mapper_name_local(profileName), ...
    "pipeline", local_profile_tx_pipeline_local(profileName), ...
    "capabilities", local_profile_capabilities_local(profileName), ...
    "cfg", profileTxCfg);
linkSpec.profileRx = struct( ...
    "name", profileName, ...
    "receiver", local_rx_chain_name_local(profileName), ...
    "pipeline", local_profile_rx_pipeline_local(profileName), ...
    "cfg", profileRxCfg);
linkSpec.extensions = struct( ...
    "eve", struct( ...
        "enable", false, ...
        "linkGainOffsetDb", 0, ...
        "assumptions", struct( ...
            "protocol", "protocol_aware", ...
            "fh", "known", ...
            "scramble", "known", ...
            "chaos", "wrong_key", ...
            "chaosApproxDelta", 0), ...
        "rxDiversity", profileRxCfg.rxDiversity), ...
    "warden", struct( ...
        "enable", false, ...
        "warden", struct( ...
            "enable", false, ...
            "pfaTarget", 0.01, ...
            "nObs", 4096, ...
            "nTrials", 200, ...
            "useParallel", false, ...
            "nWorkers", 0, ...
            "referenceLink", "independent", ...
            "linkGainOffsetDb", -10, ...
            "primaryLayer", local_default_warden_primary_layer_local(profileName), ...
            "enabledLayers", local_default_warden_layers_local(profileName), ...
            "noiseUncertaintyDb", 1.0, ...
            "extraDelaySamples", 4096, ...
            "fhNarrowband", struct("enable", true, "nFreqs", profileTxCfg.fh.nFreqs, "scanAllBins", true), ...
            "cyclostationary", struct("enable", true, "sps", commonTx.waveform.sps))), ...
    "ml", struct( ...
        "strictModelLoad", logical(opts.strictModelLoad), ...
        "requireTrainedModels", logical(opts.requireTrainedMlModels), ...
        "allowBatchModelFallback", logical(opts.allowBatchModelFallback), ...
        "loadModels", requestedModels, ...
        "preloaded", struct()), ...
    "adaptiveFrontEnd", struct("enable", false, "methods", strings(1, 0), "binding", struct()), ...
    "mixedInterference", struct("enable", false), ...
    "trainingArtifacts", struct("enable", false), ...
    "sessionControl", struct( ...
        "enable", session_frame_enabled(commonTx.control), ...
        "mode", string(session_transport_mode(commonTx.control))));
end

function commonTx = local_common_tx_defaults_local()
commonTx = struct();
commonTx.pipeline = [ ...
    "source", ...
    "payload_codec", ...
    "security_adapter", ...
    "packetize", ...
    "outer_rs", ...
    "session_control", ...
    "common_header", ...
    "inner_fec", ...
    "interleave", ...
    "modulate", ...
    "profile_mapper", ...
    "pulse_shaping"];
commonTx.tx = struct("powerBackoffDb", 0);
commonTx.source = struct( ...
    "useBuiltinImage", true, ...
    "imagePath", "", ...
    "grayscale", true, ...
    "resizeTo", [], ...
    "maxDimension", 256);
commonTx.payload = struct( ...
    "bitsPerPixel", 8, ...
    "codec", "toolbox_image", ...
    "dct", struct( ...
        "blockSize", 8, ...
        "keepRows", 4, ...
        "keepCols", 4, ...
        "quantStep", 16), ...
    "toolboxImage", struct( ...
        "format", "jp2", ...
        "mode", "lossy", ...
        "compressionRatio", 8, ...
        "quality", 75));
commonTx.security = struct( ...
    "chaosEncrypt", struct("enable", true, "packetIndependent", true), ...
    "scramble", struct("enable", false));
commonTx.packet = struct( ...
    "enable", true, ...
    "payloadBitsPerPacket", 4096, ...
    "concealLostPackets", false);
commonTx.outerRs = struct( ...
    "enable", true, ...
    "dataPacketsPerBlock", 6, ...
    "parityPacketsPerBlock", 2);
commonTx.control = struct( ...
    "sessionHeaderMode", "embedded_each_frame", ...
    "sessionFrameRepeatCount", 3, ...
    "sessionStrongRepeat", 8, ...
    "sessionMagic16", uint16(hex2dec('C7E1')), ...
    "phyHeaderMode", "compact_fec", ...
    "phyMagic16", uint16(hex2dec('3AC5')), ...
    "preambleLength", 63, ...
    "packetSyncLength", 31, ...
    "preambleType", "pn", ...
    "packetSyncType", "pn", ...
    "packetSyncPnPolynomial", [1 0 0 1 0 1], ...
    "packetSyncPnInit", [0 0 0 0 1], ...
    "preamblePnPolynomial", [1 0 0 0 1 0 0 1], ...
    "preamblePnInit", [0 0 0 0 0 0 1], ...
    "resyncIntervalPackets", 0, ...
    "phyHeaderFhEnable", false, ...
    "phyHeaderFhMode", 'slow', ...
    "phyHeaderFhHopsPerSymbol", 2, ...
    "phyHeaderFhSequenceType", 'linear', ...
    "phyHeaderFhFreqSet", [], ...
    "phyHeaderRepeat", 3, ...
    "phyHeaderRepeatCompact", 1, ...
    "phyHeaderSpreadFactor", 1, ...
    "phyHeaderSpreadSequenceType", 'pn', ...
    "phyHeaderSpreadPolynomial", [1 0 0 0 0 0 0 0 0 1 0 1], ...
    "phyHeaderSpreadInit", [0 0 0 0 0 0 0 0 0 1 1], ...
    "phyHeaderSoftBits", 5, ...
    "phyHeaderPilotLength", 0, ...
    "phyHeaderPilotPolynomial", [1 0 0 1 1], ...
    "phyHeaderPilotInit", [0 0 0 1], ...
    "sessionHeaderBodyDiversity", struct("enable", false, "copies", 1, "freqSet", []), ...
    "preambleDiversity", struct("enable", false, "copies", 1, "freqSet", []), ...
    "phyHeaderDiversity", struct("enable", false, "copies", 1));
commonTx.innerCode = struct( ...
    "kind", "conv", ...
    "trellis", poly2trellis(7, [171 133]), ...
    "decisionType", "soft", ...
    "softBits", 5, ...
    "tracebackDepth", 48, ...
    "opmode", 'trunc', ...
    "ldpc", struct( ...
        "rate", "1/2", ...
        "frameType", "short", ...
        "maxIterations", 8, ...
        "minSumScalingFactor", 0.75, ...
        "minSumOffset", 0.0, ...
        "termination", "early", ...
        "multithreaded", false));
commonTx.interleaver = struct("enable", true, "nRows", 32);
commonTx.modulation = struct("type", "BPSK");
commonTx.waveform = struct( ...
    "enable", false, ...
    "sampleRateHz", 40e3, ...
    "sps", 1, ...
    "rolloff", 0.25, ...
    "spanSymbols", 6, ...
    "rxMatchedFilter", true);
end

function channel = local_channel_defaults_local()
channel = struct();
channel.impulseProb = 0.0;
channel.impulseWeight = 0.0;
channel.impulseToBgRatio = 0.0;
channel.maxDelaySymbols = 24;
channel.singleTone = struct( ...
    "enable", false, ...
    "weight", 0.0, ...
    "power", 0.0, ...
    "normFreq", 0.05, ...
    "randomPhase", true);
channel.narrowband = struct( ...
    "enable", false, ...
    "weight", 0.0, ...
    "power", 0.0, ...
    "centerFreqPoints", 0, ...
    "bandwidthFreqPoints", 1);
channel.sweep = struct( ...
    "enable", false, ...
    "weight", 0.0, ...
    "power", 0.0, ...
    "startFreq", -0.15, ...
    "stopFreq", 0.15, ...
    "periodSymbols", 128, ...
    "randomPhase", true);
channel.multipath = struct( ...
    "enable", false, ...
    "pathDelaysSymbols", [0 1 2], ...
    "pathGainsDb", [0 -8 -14], ...
    "rayleigh", true);
channel.syncImpairment = struct( ...
    "enable", false, ...
    "timingOffsetSymbols", 0, ...
    "phaseOffsetRad", 0);
end

function [commonTx, channel, profileTxCfg, profileRxCfg] = local_apply_profile_defaults_local(commonTx, channel, profileName)
profileTxCfg = struct( ...
    "dsss", struct("enable", false, "spreadFactor", 1, "sequenceType", 'pn', ...
        "pnPolynomial", [1 0 0 0 0 0 0 0 0 1 0 1], "pnInit", [0 0 0 0 0 0 0 0 0 1 1]), ...
    "fh", struct( ...
        "enable", false, ...
        "mode", 'slow', ...
        "nFreqs", 1, ...
        "freqSet", 0, ...
        "sequenceType", 'chaos', ...
        "balanceMode", "none", ...
        "pnPolynomial", [1 0 0 0 0 0 0 0 0 1 0 1], ...
        "pnInit", [0 0 0 0 0 0 0 0 0 1 1], ...
        "chaosMethod", 'logistic', ...
        "chaosParams", struct( ...
            "mu", 3.9999, ...
            "x0", 0.3141592653589793, ...
            "a", 1.4, ...
            "b", 0.3, ...
            "y0", 0.123456789), ...
        "symbolsPerHop", 64, ...
        "payloadDiversity", struct("enable", false, "copies", 2, "indexOffset", 1)), ...
    "scFde", struct( ...
        "enable", false, ...
        "cpLenSymbols", 8, ...
        "pilotLength", 8, ...
        "lambdaFactor", 0.05, ...
        "pilotMinAbsGain", 0.05, ...
        "pilotMseReference", 0.5, ...
        "fdePilotMseThreshold", 2.5, ...
        "fdePilotMseMargin", 1.0, ...
        "minReliability", 0.05, ...
        "pilotPolynomial", [1 0 0 0 1 1], ...
        "pilotInit", [1 0 0 1 1]));

profileRxCfg = struct( ...
    "methods", strings(1, 0), ...
    "allowedMethods", strings(1, 0), ...
    "mitigation", local_mitigation_defaults_local(), ...
    "softMetric", struct("clipA", 4.0), ...
    "sync", local_rx_sync_defaults_local(), ...
    "rxDiversity", struct("enable", false, "nRx", 1, "combineMethod", "mrc"));

switch profileName
    case "impulse"
        commonTx.waveform.enable = true;
        commonTx.waveform.sampleRateHz = 160e3;
        commonTx.waveform.sps = 4;
        commonTx.waveform.rolloff = 0.25;
        commonTx.waveform.spanSymbols = 6;
        commonTx.control.sessionHeaderMode = "session_frame_repeat";
        commonTx.control.sessionFrameRepeatCount = 2;
        commonTx.control.preambleLength = 63;
        commonTx.control.packetSyncLength = 63;
        commonTx.control.resyncIntervalPackets = 0;
        commonTx.control.phyHeaderFhEnable = false;
        commonTx.control.phyHeaderRepeatCompact = 2;
        commonTx.control.phyHeaderSpreadFactor = 4;
        commonTx.packet.payloadBitsPerPacket = 4096;
        commonTx.modulation.type = "QPSK";
        commonTx.outerRs.dataPacketsPerBlock = 8;
        commonTx.outerRs.parityPacketsPerBlock = 2;

        channel.impulseProb = 0.03;
        channel.impulseWeight = 1.0;
        channel.multipath.enable = false;
        channel.narrowband.enable = false;
        channel.narrowband.weight = 0.0;

        profileTxCfg.fh.enable = true;
        profileTxCfg.fh.nFreqs = 3;
        profileTxCfg.fh.freqSet = [];
        profileTxCfg.fh.sequenceType = 'chaos';
        profileTxCfg.fh.symbolsPerHop = 64;
        profileTxCfg.scFde.enable = false;

        profileRxCfg.methods = "blanking";
        profileRxCfg.allowedMethods = ["none" "clipping" "blanking" "adaptive_notch" "fft_notch" "stft_notch" ...
            "ml_blanking" "ml_cnn" "ml_cnn_hard" "ml_gru" "ml_gru_hard"];
        profileRxCfg.sync.multipathEq.enable = false;

    case "narrowband"
        commonTx.waveform.enable = true;
        commonTx.waveform.sampleRateHz = 300e3;
        commonTx.waveform.sps = 10;
        commonTx.waveform.rolloff = 0.25;
        commonTx.waveform.spanSymbols = 6;
        commonTx.control.preambleLength = 63;
        commonTx.control.packetSyncLength = 63;
        commonTx.control.resyncIntervalPackets = 1;
        commonTx.control.sessionHeaderMode = "embedded_each_frame";
        commonTx.control.sessionFrameRepeatCount = 2;
        commonTx.control.phyHeaderFhEnable = true;
        commonTx.control.phyHeaderRepeatCompact = 2;
        commonTx.control.phyHeaderSpreadFactor = 2;
        commonTx.control.preambleDiversity.enable = true;
        commonTx.control.preambleDiversity.copies = 2;
        commonTx.control.preambleDiversity.freqSet = [-4.375 4.375];
        commonTx.control.sessionHeaderBodyDiversity.enable = true;
        commonTx.control.sessionHeaderBodyDiversity.copies = 2;
        commonTx.control.sessionHeaderBodyDiversity.freqSet = [-4.375 4.375];
        commonTx.control.phyHeaderDiversity.enable = true;
        commonTx.control.phyHeaderDiversity.copies = 2;
        commonTx.control.phyHeaderFhFreqSet = [-4.375 -0.625 0.625 4.375];
        commonTx.packet.payloadBitsPerPacket = 8192;
        commonTx.outerRs.dataPacketsPerBlock = 4;
        commonTx.outerRs.parityPacketsPerBlock = 4;

        channel.impulseProb = 0.0;
        channel.impulseWeight = 0.0;
        channel.narrowband.enable = true;
        channel.narrowband.weight = 1.0;
        channel.narrowband.centerFreqPoints = 0;
        channel.narrowband.bandwidthFreqPoints = 1;
        channel.multipath.enable = false;

        profileTxCfg.fh.enable = true;
        profileTxCfg.fh.nFreqs = 8;
        profileTxCfg.fh.freqSet = [-4.375 -3.125 -1.875 -0.625 0.625 1.875 3.125 4.375];
        profileTxCfg.fh.sequenceType = 'chaos';
        profileTxCfg.fh.balanceMode = "permutation_block";
        profileTxCfg.fh.symbolsPerHop = 48;
        profileTxCfg.fh.payloadDiversity.enable = false;
        profileTxCfg.fh.payloadDiversity.copies = 1;
        profileTxCfg.fh.payloadDiversity.indexOffset = 3;
        profileTxCfg.dsss.enable = true;
        profileTxCfg.dsss.spreadFactor = 4;
        profileTxCfg.scFde.enable = false;

        profileRxCfg.methods = "fh_erasure";
        profileRxCfg.allowedMethods = ["none" "fh_erasure" "narrowband_notch_soft" ...
            "narrowband_subband_excision_soft" "narrowband_cnn_residual_soft"];
        profileRxCfg.sync.multipathEq.enable = false;
        profileRxCfg.mitigation.headerBandstop.enable = true;
        profileRxCfg.mitigation.headerDecodeDiversity.enable = true;

    case "rayleigh_multipath"
        commonTx.waveform.enable = true;
        commonTx.waveform.sampleRateHz = 240e3;
        commonTx.waveform.sps = 4;
        commonTx.waveform.rolloff = 0.25;
        commonTx.waveform.spanSymbols = 6;
        commonTx.control.sessionHeaderMode = "session_frame_repeat";
        commonTx.control.sessionFrameRepeatCount = 2;
        commonTx.control.preambleLength = 127;
        commonTx.control.packetSyncLength = 63;
        commonTx.control.resyncIntervalPackets = 1;
        commonTx.control.phyHeaderFhEnable = false;
        commonTx.control.phyHeaderRepeatCompact = 2;
        commonTx.control.phyHeaderSpreadFactor = 2;
        commonTx.packet.payloadBitsPerPacket = 6144;
        commonTx.outerRs.dataPacketsPerBlock = 6;
        commonTx.outerRs.parityPacketsPerBlock = 3;

        channel.impulseProb = 0.0;
        channel.impulseWeight = 0.0;
        channel.narrowband.enable = false;
        channel.narrowband.weight = 0.0;
        channel.multipath.enable = true;
        channel.multipath.pathDelaysSymbols = [0 2 4];
        channel.multipath.pathGainsDb = [0 -6 -10];
        channel.multipath.rayleigh = true;

        profileTxCfg.fh.enable = true;
        profileTxCfg.fh.nFreqs = 3;
        profileTxCfg.fh.freqSet = [];
        profileTxCfg.fh.sequenceType = 'chaos';
        profileTxCfg.fh.symbolsPerHop = 96;
        profileTxCfg.scFde.enable = true;
        profileTxCfg.scFde.cpLenSymbols = 16;
        profileTxCfg.scFde.pilotLength = 8;
        profileTxCfg.scFde.lambdaFactor = 1.0;
        profileTxCfg.scFde.pilotMseReference = 0.35;

        profileRxCfg.methods = "sc_fde_mmse";
        profileRxCfg.allowedMethods = ["none" "sc_fde_mmse"];
        profileRxCfg.sync.compensateCarrier = false;
        profileRxCfg.sync.multipathEq.enable = true;
        profileRxCfg.sync.multipathEq.nTaps = 9;
        profileRxCfg.sync.multipathEq.lambdaFactor = 1.0;
        profileRxCfg.sync.multipathEq.compareMethods = "sc_fde_mmse";
        profileRxCfg.rxDiversity.enable = true;
        profileRxCfg.rxDiversity.nRx = 2;
        profileRxCfg.rxDiversity.combineMethod = "mrc";

    case "robust_unified"
        commonTx.waveform.enable = true;
        commonTx.waveform.sampleRateHz = 240e3;
        commonTx.waveform.sps = 4;
        commonTx.waveform.rolloff = 0.25;
        commonTx.waveform.spanSymbols = 6;
        commonTx.control.sessionHeaderMode = "embedded_each_frame";
        commonTx.control.sessionFrameRepeatCount = 2;
        commonTx.control.preambleLength = 127;
        commonTx.control.packetSyncLength = 63;
        commonTx.control.resyncIntervalPackets = 1;
        commonTx.control.phyHeaderFhEnable = true;
        commonTx.control.phyHeaderRepeatCompact = 2;
        commonTx.control.phyHeaderSpreadFactor = 2;
        commonTx.control.preambleDiversity.enable = true;
        commonTx.control.preambleDiversity.copies = 2;
        commonTx.control.preambleDiversity.freqSet = [];
        commonTx.control.sessionHeaderBodyDiversity.enable = true;
        commonTx.control.sessionHeaderBodyDiversity.copies = 2;
        commonTx.control.sessionHeaderBodyDiversity.freqSet = [];
        commonTx.control.phyHeaderDiversity.enable = true;
        commonTx.control.phyHeaderDiversity.copies = 2;
        commonTx.control.phyHeaderFhFreqSet = [];
        commonTx.packet.payloadBitsPerPacket = 8192;
        commonTx.outerRs.dataPacketsPerBlock = 4;
        commonTx.outerRs.parityPacketsPerBlock = 6;

        channel.impulseProb = 0.0;
        channel.impulseWeight = 0.0;
        channel.narrowband.enable = false;
        channel.narrowband.weight = 0.0;
        channel.narrowband.centerFreqPoints = 0;
        channel.narrowband.bandwidthFreqPoints = 1;
        channel.multipath.enable = false;
        channel.multipath.pathDelaysSymbols = [0 2 4];
        channel.multipath.pathGainsDb = [0 -6 -10];
        channel.multipath.rayleigh = true;

        profileTxCfg.fh.enable = true;
        profileTxCfg.fh.nFreqs = 3;
        profileTxCfg.fh.freqSet = [];
        profileTxCfg.fh.sequenceType = 'chaos';
        profileTxCfg.fh.balanceMode = "permutation_block";
        profileTxCfg.fh.symbolsPerHop = 96;
        profileTxCfg.fh.payloadDiversity.enable = false;
        profileTxCfg.fh.payloadDiversity.copies = 1;
        profileTxCfg.fh.payloadDiversity.indexOffset = 3;
        profileTxCfg.dsss.enable = true;
        profileTxCfg.dsss.spreadFactor = 4;
        profileTxCfg.scFde.enable = true;
        profileTxCfg.scFde.cpLenSymbols = 16;
        profileTxCfg.scFde.pilotLength = 8;
        profileTxCfg.scFde.lambdaFactor = 1.0;
        profileTxCfg.scFde.pilotMseReference = 0.35;

        profileRxCfg.methods = "robust_combo";
        profileRxCfg.allowedMethods = "robust_combo";
        profileRxCfg.sync.compensateCarrier = false;
        profileRxCfg.sync.multipathEq.enable = true;
        profileRxCfg.sync.multipathEq.nTaps = 9;
        profileRxCfg.sync.multipathEq.lambdaFactor = 1.0;
        profileRxCfg.sync.multipathEq.compareMethods = "robust_combo";
        profileRxCfg.mitigation.headerBandstop.enable = true;
        profileRxCfg.mitigation.headerDecodeDiversity.enable = true;
        profileRxCfg.rxDiversity.enable = true;
        profileRxCfg.rxDiversity.nRx = 2;
        profileRxCfg.rxDiversity.combineMethod = "mrc";

    otherwise
        error("Unexpected profile name: %s", char(profileName));
end
end

function mitigation = local_mitigation_defaults_local()
mitigation = struct();
mitigation.thresholdStrategy = "median";
mitigation.thresholdAlpha = 4.0;
mitigation.thresholdFixed = 3.0;
mitigation.blankingHold = 1;
mitigation.binding = struct( ...
    "enable", true, ...
    "impulseMethods", ["none" "blanking" "clipping" "adaptive_notch" "fft_notch" "stft_notch" ...
        "ml_blanking" "ml_cnn" "ml_cnn_hard" "ml_gru" "ml_gru_hard"], ...
    "singleToneMethods", ["none" "fft_notch" "adaptive_notch"], ...
    "narrowbandMethods", ["none" "fh_erasure" "narrowband_notch_soft" ...
        "narrowband_subband_excision_soft" "narrowband_cnn_residual_soft"], ...
    "sweepMethods", ["none" "stft_notch" "adaptive_notch"], ...
    "multipathMethods", ["none" "sc_fde_mmse"], ...
    "mixedMethods", "none");
mitigation.fftBandstop = struct( ...
    "peakRatio", 8, ...
    "maxNotches", 2, ...
    "notchHalfWidth", 1, ...
    "minFreqAbs", 0.01);
mitigation.adaptiveNotch = struct( ...
    "peakRatio", 8, ...
    "radius", 0.97, ...
    "minFreqAbs", 0.01, ...
    "stages", 1);
mitigation.stftNotch = struct( ...
    "fftLength", 128, ...
    "hopLength", 32, ...
    "peakRatio", 8, ...
    "maxNotches", 2, ...
    "notchHalfWidth", 1, ...
    "minFreqAbs", 0.01);
mitigation.headerBandstop = struct( ...
    "enable", false, ...
    "peakRatio", 6, ...
    "edgeRatio", 2.5, ...
    "maxBands", 1, ...
    "mergeGapBins", 2, ...
    "padBins", 1, ...
    "minBandBins", 3, ...
    "smoothSpanBins", 7, ...
    "fftOversample", 4, ...
    "maxBandwidthFrac", 0.22, ...
    "minFreqAbs", 0.01, ...
    "suppressToFloor", true);
mitigation.headerDecodeDiversity = struct( ...
    "enable", false, ...
    "actions", ["none" "fft_bandstop" "adaptive_notch"]);
mitigation.fhErasure = struct( ...
    "freqPowerRatioThreshold", 1.35, ...
    "hopPowerRatioThreshold", 1.55, ...
    "minReliability", 0.02, ...
    "softSlope", 12.0, ...
    "maxErasedFreqFraction", 0.75, ...
    "edgeGuardSymbols", 2, ...
    "attenuateSymbols", true, ...
    "lowPowerFadeEnable", true, ...
    "lowFreqPowerRatioThreshold", 0.75, ...
    "lowHopPowerRatioThreshold", 0.70, ...
    "lowPowerSoftSlope", 8.0, ...
    "constellationMseEnable", true, ...
    "constellationMseThreshold", 0.22, ...
    "constellationMseSoftSlope", 8.0, ...
    "freqConstellationMseEnable", true, ...
    "freqConstellationMseRatioThreshold", 1.05, ...
    "freqConstellationMseFloor", 0.03, ...
    "freqBandstopEnable", true, ...
    "freqBandstopObservationSymbols", 128, ...
    "freqBandstopPeakRatio", 2.2, ...
    "freqBandstopEdgeRatio", 1.2, ...
    "freqBandstopMinFreqAbs", 0.005, ...
    "freqBandstopMaxBandwidthFrac", 0.18, ...
    "mlFreqProbabilityThreshold", 0.65, ...
    "mlMaxErasedFreqFraction", 0.25, ...
    "mlProbabilitySlope", 120.0, ...
    "mlRequirePowerEvidence", true, ...
    "multipathFadeEnable", false);
mitigation.narrowbandNotchSoft = struct( ...
    "observationSymbolsPerFreq", 144, ...
    "minObservationSymbolsPerFreq", 48, ...
    "edgeGuardSymbols", 2, ...
    "minReliability", 0.08, ...
    "maskFractionPenaltySlope", 0.20, ...
    "powerRemovalPenaltySlope", 0.35, ...
    "attenuateSymbols", false, ...
    "bandstop", struct( ...
        "peakRatio", 2.2, ...
        "edgeRatio", 1.2, ...
        "maxBands", 1, ...
        "mergeGapBins", 2, ...
        "padBins", 1, ...
        "minBandBins", 3, ...
        "smoothSpanBins", 7, ...
        "fftOversample", 4, ...
        "maxBandwidthFrac", 0.18, ...
        "minFreqAbs", 0.005, ...
        "suppressToFloor", true));
end

function rxSync = local_rx_sync_defaults_local()
rxSync = struct();
rxSync.fineSearchRadius = 1;
rxSync.compensateCarrier = false;
rxSync.enableFractionalTiming = false;
rxSync.estimateCfo = false;
rxSync.maxShortSyncMisses = 1;
rxSync.carrierPll = struct("enable", false);
rxSync.timingDll = struct("enable", false);
rxSync.multipathEq = struct( ...
    "enable", false, ...
    "method", "mmse", ...
    "nTaps", 9, ...
    "lambdaFactor", 0.05, ...
    "compareMethods", strings(1, 0), ...
    "frequencyOffsets", 0);
end

function pipeline = local_profile_tx_pipeline_local(profileName)
switch profileName
    case "impulse"
        pipeline = ["packet_burst_mapper" "chaos_fh_payload_mapper"];
    case "narrowband"
        pipeline = ["guarded_control_mapper" "chaos_fh_payload_mapper"];
    case "rayleigh_multipath"
        pipeline = ["guarded_control_mapper" "sc_fde_mapper" "chaos_fh_payload_mapper"];
    case "robust_unified"
        pipeline = ["guarded_control_mapper" "dsss_mapper" "sc_fde_mapper" "chaos_fh_payload_mapper"];
    otherwise
        error("Unexpected profile name: %s", char(profileName));
end
end

function pipeline = local_profile_rx_pipeline_local(profileName)
switch profileName
    case "impulse"
        pipeline = [ ...
            "session_layer", ...
            "capture_sync", ...
            "impulse_suppression", ...
            "common_header_decode", ...
            "payload_demod_fec", ...
            "outer_rs", ...
            "payload_recovery"];
    case "narrowband"
        pipeline = [ ...
            "session_layer", ...
            "capture_sync", ...
            "protected_control_acquisition", ...
            "fh_narrowband_estimate_erasure", ...
            "common_header_decode", ...
            "payload_soft_erasure_demod_fec", ...
            "outer_rs"];
    case "rayleigh_multipath"
        pipeline = [ ...
            "session_layer", ...
            "capture_sync", ...
            "preamble_channel_estimate", ...
            "header_equalization", ...
            "common_header_decode", ...
            "sc_fde_payload_equalization", ...
            "demod_fec", ...
            "outer_rs"];
    case "robust_unified"
        pipeline = [ ...
            "session_layer", ...
            "capture_sync", ...
            "impulse_blanking", ...
            "protected_control_acquisition", ...
            "fh_narrowband_erasure", ...
            "sc_fde_payload_equalization", ...
            "dsss_despread_demod_fec", ...
            "outer_rs"];
    otherwise
        error("Unexpected profile name: %s", char(profileName));
end
end

function mapperName = local_tx_mapper_name_local(profileName)
switch profileName
    case "impulse"
        mapperName = "impulse_packet_burst_mapper";
    case "narrowband"
        mapperName = "narrowband_fh_mapper";
    case "rayleigh_multipath"
        mapperName = "rayleigh_sc_fde_mapper";
    case "robust_unified"
        mapperName = "robust_fh_dsss_scfde_mapper";
    otherwise
        error("Unexpected profile name: %s", char(profileName));
end
end

function chainName = local_rx_chain_name_local(profileName)
switch profileName
    case "impulse"
        chainName = "run_impulse_rx";
    case "narrowband"
        chainName = "run_narrowband_rx";
    case "rayleigh_multipath"
        chainName = "run_rayleigh_multipath_rx";
    case "robust_unified"
        chainName = "run_rayleigh_multipath_rx";
    otherwise
        error("Unexpected profile name: %s", char(profileName));
end
end

function capabilities = local_profile_capabilities_local(profileName)
switch profileName
    case "impulse"
        capabilities = struct("fh", true, "dsss", false, "scFde", false);
    case "narrowband"
        capabilities = struct("fh", true, "dsss", true, "scFde", false);
    case "rayleigh_multipath"
        capabilities = struct("fh", true, "dsss", false, "scFde", true);
    case "robust_unified"
        capabilities = struct("fh", true, "dsss", true, "scFde", true);
    otherwise
        error("Unexpected profile name: %s", char(profileName));
end
end

function layerNames = local_default_warden_layers_local(profileName)
switch profileName
    case "impulse"
        layerNames = "energyNp";
    case "narrowband"
        layerNames = ["energyOptUncertain" "cyclostationaryOpt"];
    case "rayleigh_multipath"
        layerNames = ["energyOptUncertain" "cyclostationaryOpt"];
    case "robust_unified"
        layerNames = ["energyNp" "energyOptUncertain"];
    otherwise
        error("Unexpected profile name: %s", char(profileName));
end
end

function layerName = local_default_warden_primary_layer_local(profileName)
switch profileName
    case "impulse"
        layerName = "energyNp";
    case "narrowband"
        layerName = "energyOptUncertain";
    case "rayleigh_multipath"
        layerName = "energyOptUncertain";
    case "robust_unified"
        layerName = "energyOptUncertain";
    otherwise
        error("Unexpected profile name: %s", char(profileName));
end
end
