function export_thesis_tables(outDir, results)
%EXPORT_THESIS_TABLES  Export thesis-friendly CSV tables from simulation results.
%
% 输入:
%   outDir  - 输出目录（必须已存在）
%   results - simulate() 返回的结果结构体
%
% 输出:
%   无（直接写 CSV 到磁盘）

arguments
    outDir {mustBeTextScalar}
    results (1,1) struct
end

outDir = string(outDir);
if ~isfolder(outDir)
    error("export_thesis_tables:MissingOutputDir", ...
        "Output directory does not exist: %s", outDir);
end

local_require_fields(results, ["methods" "ebN0dB" "jsrDb" "scan" "ber" "rawPer" "per" "packetDiagnostics" "linkBudget" "spectrum" "tx" "params"]);
local_require_fields(results.packetDiagnostics, "bob", "results.packetDiagnostics");
local_require_fields(results.linkBudget, "bob", "results.linkBudget");
local_require_fields(results.params, ["sim" "mod" "payload" "frame" "fh" "channel" "fec" "dsss" "rxDiversity"], "results.params");
local_require_fields(results, "kl", "results");

methods = string(results.methods(:));
bobEbN0dB = double(results.ebN0dB(:));
bobJsrDb = double(results.jsrDb(:));
nMethods = numel(methods);
nPoints = numel(bobEbN0dB);
if numel(bobJsrDb) ~= nPoints
    error("export_thesis_tables:InvalidJsrPointCount", ...
        "results.jsrDb must contain %d points, got %d.", nPoints, numel(bobJsrDb));
end

berBob = local_require_metric_matrix(results.ber, nMethods, nPoints, "results.ber");
rawPerBob = local_require_metric_matrix(results.rawPer, nMethods, nPoints, "results.rawPer");
perBob = local_require_metric_matrix(results.per, nMethods, nPoints, "results.per");
[commMetricsBob, compMetricsBob] = local_get_image_metrics(results, nMethods, nPoints, "results");
scan = local_require_scan_struct(results.scan, nPoints, "results.scan");

bobDiag = results.packetDiagnostics.bob;
frontEndBob = local_require_point_vector(bobDiag, "frontEndSuccessRate", nPoints, "results.packetDiagnostics.bob");
headerBob = local_require_point_vector(bobDiag, "headerSuccessRate", nPoints, "results.packetDiagnostics.bob");
payloadBob = local_require_method_point_matrix(bobDiag, "payloadSuccessRate", nMethods, nPoints, "results.packetDiagnostics.bob");
rawPayloadBob = local_require_method_point_matrix(bobDiag, "rawPayloadSuccessRate", nMethods, nPoints, "results.packetDiagnostics.bob");

bobBudget = local_require_budget_struct(results.linkBudget.bob, nPoints, "results.linkBudget.bob");

runSummary = local_build_run_summary_table(results, methods, nMethods, nPoints, scan);
pointOverview = local_build_point_overview_table( ...
    bobEbN0dB, bobJsrDb, bobBudget, scan, frontEndBob, headerBob, results, nPoints);
metricsBob = local_build_metric_table( ...
    methods, "bob", bobBudget.txPowerDb, bobEbN0dB, bobJsrDb, scan, berBob, rawPerBob, perBob, rawPayloadBob, payloadBob, ...
    commMetricsBob, compMetricsBob, frontEndBob, headerBob);

writetable(runSummary, fullfile(outDir, "run_summary.csv"));
writetable(pointOverview, fullfile(outDir, "points_overview.csv"));
writetable(metricsBob, fullfile(outDir, "metrics_bob.csv"));

if isfield(results, "eve")
    local_require_fields(results.eve, ["ebN0dB" "ber" "rawPer" "per" "packetDiagnostics"], "results.eve");
    local_require_fields(results.packetDiagnostics, "bob", "results.packetDiagnostics");
    if ~isfield(results.linkBudget, "eve")
        error("export_thesis_tables:MissingEveBudget", ...
            "results.linkBudget.eve is required when results.eve is present.");
    end

    eveEbN0dB = double(results.eve.ebN0dB(:));
    if numel(eveEbN0dB) ~= nPoints
        error("export_thesis_tables:InvalidEveEbN0", ...
            "results.eve.ebN0dB must contain %d points, got %d.", nPoints, numel(eveEbN0dB));
    end

    berEve = local_require_metric_matrix(results.eve.ber, nMethods, nPoints, "results.eve.ber");
    rawPerEve = local_require_metric_matrix(results.eve.rawPer, nMethods, nPoints, "results.eve.rawPer");
    perEve = local_require_metric_matrix(results.eve.per, nMethods, nPoints, "results.eve.per");
    [commMetricsEve, compMetricsEve] = local_get_image_metrics(results.eve, nMethods, nPoints, "results.eve");

    eveDiag = results.eve.packetDiagnostics;
    frontEndEve = local_require_point_vector(eveDiag, "frontEndSuccessRate", nPoints, "results.eve.packetDiagnostics");
    headerEve = local_require_point_vector(eveDiag, "headerSuccessRate", nPoints, "results.eve.packetDiagnostics");
    payloadEve = local_require_method_point_matrix(eveDiag, "payloadSuccessRate", nMethods, nPoints, "results.eve.packetDiagnostics");
    rawPayloadEve = local_require_method_point_matrix(eveDiag, "rawPayloadSuccessRate", nMethods, nPoints, "results.eve.packetDiagnostics");

    eveBudget = local_require_budget_struct(results.linkBudget.eve, nPoints, "results.linkBudget.eve");

    metricsEve = local_build_metric_table( ...
        methods, "eve", eveBudget.txPowerDb, eveEbN0dB, bobJsrDb, scan, berEve, rawPerEve, perEve, rawPayloadEve, payloadEve, ...
        commMetricsEve, compMetricsEve, frontEndEve, headerEve);
    writetable(metricsEve, fullfile(outDir, "metrics_eve.csv"));
end

if isfield(results, "covert") && isfield(results.covert, "warden")
    wardenTable = local_build_warden_table(results.covert.warden, bobEbN0dB, bobJsrDb, scan, nPoints);
    writetable(wardenTable, fullfile(outDir, "warden_layers.csv"));
end
end

function t = local_build_run_summary_table(results, methods, nMethods, nPoints, scan)
packetConcealActive = false;
packetConcealMode = "";
if isfield(results, "packetConceal")
    if isfield(results.packetConceal, "active")
        packetConcealActive = logical(results.packetConceal.active);
    end
    if isfield(results.packetConceal, "mode")
        packetConcealMode = string(results.packetConceal.mode);
    end
end

eveEnable = isfield(results, "eve");
wardenEnable = isfield(results, "covert") && isfield(results.covert, "warden");

eveScramble = "";
eveFh = "";
eveChaos = "";
eveChaosApproxDelta = NaN;
if eveEnable && isfield(results.eve, "assumptions")
    assump = results.eve.assumptions;
    local_require_fields(assump, ["scramble" "fh" "chaos" "chaosApproxDelta"], "results.eve.assumptions");
    eveScramble = string(assump.scramble);
    eveFh = string(assump.fh);
    eveChaos = string(assump.chaos);
    eveChaosApproxDelta = double(assump.chaosApproxDelta);
end

wardenPrimaryLayer = "";
if wardenEnable && isfield(results.covert.warden, "primaryLayer")
    wardenPrimaryLayer = string(results.covert.warden.primaryLayer);
end

channelCfg = local_require_channel_config(results.params.channel, "results.params.channel");
rxDivCfg = local_require_rx_diversity_config(results.params.rxDiversity, "results.params.rxDiversity");
[enabledInterferenceTypes, enabledInterferenceCount] = local_collect_enabled_interference_types(channelCfg);
fecInfo = fec_get_info(results.params.fec);
ldpcRateName = "";
ldpcFrameType = "";
ldpcInfoBits = NaN;
ldpcBlockLength = NaN;
ldpcMaxIterations = NaN;
if fecInfo.kind == "ldpc"
    ldpcRateName = string(fecInfo.ldpcRateName);
    ldpcFrameType = string(fecInfo.ldpcFrameType);
    ldpcInfoBits = double(fecInfo.numInfoBits);
    ldpcBlockLength = double(fecInfo.blockLength);
    ldpcMaxIterations = double(fecInfo.ldpcMaxIterations);
end

eveRxDivEnable = false;
eveRxDivNRx = NaN;
eveRxDivMethod = "";
if eveEnable
    if ~(isfield(results.params, "eve") && isstruct(results.params.eve) && isfield(results.params.eve, "rxDiversity"))
        error("export_thesis_tables:MissingEveRxDiversity", ...
            "results.params.eve.rxDiversity is required when Eve is enabled.");
    end
    eveRxDivCfg = local_require_rx_diversity_config(results.params.eve.rxDiversity, "results.params.eve.rxDiversity");
    eveRxDivEnable = logical(eveRxDivCfg.enable);
    eveRxDivNRx = double(eveRxDivCfg.nRx);
    eveRxDivMethod = string(eveRxDivCfg.combineMethod);
end

t = table( ...
    double(results.params.rngSeed), ...
    double(results.params.sim.nFramesPerPoint), ...
    string(results.params.mod.type), ...
    string(fecInfo.kind), ...
    double(fecInfo.codeRate), ...
    ldpcRateName, ...
    ldpcFrameType, ...
    ldpcInfoBits, ...
    ldpcBlockLength, ...
    ldpcMaxIterations, ...
    string(results.params.payload.codec), ...
    string(results.params.frame.sessionHeaderMode), ...
    logical(results.params.dsss.enable), ...
    double(results.params.dsss.spreadFactor), ...
    string(results.params.dsss.sequenceType), ...
    local_join_numeric_vector(double(results.params.dsss.pnPolynomial)), ...
    local_join_numeric_vector(double(results.params.dsss.pnInit)), ...
    logical(results.params.fh.enable), ...
    logical(rxDivCfg.enable), ...
    double(rxDivCfg.nRx), ...
    string(rxDivCfg.combineMethod), ...
    logical(packetConcealActive), ...
    string(packetConcealMode), ...
    string(scan.type), ...
    local_join_numeric_vector(scan.ebN0dBList), ...
    local_join_numeric_vector(scan.jsrDbList), ...
    double(scan.nSnr), ...
    double(scan.nJsr), ...
    local_join_string_vector(methods), ...
    nMethods, ...
    nPoints, ...
    local_join_numeric_vector(results.tx.configuredPowerLin), ...
    local_join_numeric_vector(results.tx.configuredPowerDb), ...
    double(results.linkBudget.noisePsdLin), ...
    local_join_string_vector(enabledInterferenceTypes), ...
    enabledInterferenceCount, ...
    channelCfg.impulseProb, ...
    channelCfg.impulseToBgRatio, ...
    channelCfg.impulseWeight, ...
    channelCfg.singleToneEnable, ...
    channelCfg.singleToneWeight, ...
    channelCfg.singleToneFreqHz, ...
    channelCfg.singleToneRandomPhase, ...
    channelCfg.narrowbandEnable, ...
    channelCfg.narrowbandWeight, ...
    channelCfg.narrowbandCenterFreqPoints, ...
    channelCfg.narrowbandBandwidthFreqPoints, ...
    channelCfg.sweepEnable, ...
    channelCfg.sweepWeight, ...
    channelCfg.sweepStartHz, ...
    channelCfg.sweepStopHz, ...
    channelCfg.sweepPeriodSymbols, ...
    channelCfg.sweepRandomPhase, ...
    channelCfg.syncImpairmentEnable, ...
    channelCfg.syncTimingOffsetSymbols, ...
    channelCfg.syncPhaseOffsetRad, ...
    channelCfg.multipathEnable, ...
    channelCfg.multipathPathDelaysSymbols, ...
    channelCfg.multipathPathGainsDb, ...
    channelCfg.multipathRayleigh, ...
    double(results.tx.burstDurationSec), ...
    local_join_numeric_vector(results.tx.averagePowerLin), ...
    local_join_numeric_vector(results.tx.averagePowerDb), ...
    local_join_numeric_vector(results.tx.peakPowerLin), ...
    local_join_numeric_vector(results.tx.powerErrorLin), ...
    double(results.spectrum.bw99Hz), ...
    double(results.spectrum.etaBpsHz), ...
    logical(eveEnable), ...
    logical(eveRxDivEnable), ...
    eveRxDivNRx, ...
    eveRxDivMethod, ...
    logical(wardenEnable), ...
    eveScramble, ...
    eveFh, ...
    eveChaos, ...
    eveChaosApproxDelta, ...
    wardenPrimaryLayer, ...
    'VariableNames', { ...
        'rngSeed', 'nFramesPerPoint', 'modType', 'fecKind', 'fecCodeRate', ...
        'fecLdpcRate', 'fecLdpcFrameType', 'fecLdpcInfoBits', 'fecLdpcBlockLength', 'fecLdpcMaxIterations', ...
        'payloadCodec', 'sessionHeaderMode', ...
        'dsssEnable', 'dsssSpreadFactor', 'dsssSequenceType', 'dsssPnPolynomial', 'dsssPnInit', ...
        'fhEnable', 'rxDiversityEnable', 'rxDiversityNRx', 'rxDiversityCombineMethod', ...
        'packetConcealActive', 'packetConcealMode', ...
        'scanType', 'ebN0dBList', 'jsrDbList', 'nSnr', 'nJsr', ...
        'methods', 'nMethods', 'nPoints', ...
        'txConfiguredPowerLinList', 'txConfiguredPowerDbList', 'noisePsdLin', ...
        'channelEnabledInterferenceTypes', 'channelEnabledInterferenceCount', ...
        'channelImpulseProb', 'channelImpulseToBgRatio', 'channelImpulseWeight', ...
        'channelSingleToneEnable', 'channelSingleToneWeight', 'channelSingleToneFreqHz', 'channelSingleToneRandomPhase', ...
        'channelNarrowbandEnable', 'channelNarrowbandWeight', 'channelNarrowbandCenterFreqPoints', 'channelNarrowbandBandwidthFreqPoints', ...
        'channelSweepEnable', 'channelSweepWeight', 'channelSweepStartHz', 'channelSweepStopHz', 'channelSweepPeriodSymbols', 'channelSweepRandomPhase', ...
        'channelSyncImpairmentEnable', 'channelSyncTimingOffsetSymbols', 'channelSyncPhaseOffsetRad', ...
        'channelMultipathEnable', 'channelMultipathPathDelaysSymbols', 'channelMultipathPathGainsDb', 'channelMultipathRayleigh', ...
        'txBurstDurationSec', 'txMeasuredAveragePowerLinList', 'txMeasuredAveragePowerDbList', 'txPeakPowerLinList', 'txPowerErrorLinList', ...
        'bw99Hz', 'etaBpsHz', 'eveEnable', 'eveRxDiversityEnable', 'eveRxDiversityNRx', 'eveRxDiversityCombineMethod', 'wardenEnable', ...
        'eveScrambleAssumption', 'eveFhAssumption', 'eveChaosAssumption', 'eveChaosApproxDelta', ...
        'wardenPrimaryLayer'});
end

function t = local_build_point_overview_table(bobEbN0dB, bobJsrDb, bobBudget, scan, frontEndBob, headerBob, results, nPoints)
pointIndex = (1:nPoints).';
klSignalVsNoise = local_require_point_vector(results.kl, "signalVsNoise", nPoints, "results.kl");
klNoiseVsSignal = local_require_point_vector(results.kl, "noiseVsSignal", nPoints, "results.kl");
klSymmetric = local_require_point_vector(results.kl, "symmetric", nPoints, "results.kl");

eveEbN0dB = nan(nPoints, 1);
eveFrontEnd = nan(nPoints, 1);
eveHeader = nan(nPoints, 1);
if isfield(results, "eve")
    eveBudget = local_require_budget_struct(results.linkBudget.eve, nPoints, "results.linkBudget.eve");
    eveEbN0dB = double(results.eve.ebN0dB(:));
    eveDiag = results.eve.packetDiagnostics;
    eveFrontEnd = local_require_point_vector(eveDiag, "frontEndSuccessRate", nPoints, "results.eve.packetDiagnostics");
    eveHeader = local_require_point_vector(eveDiag, "headerSuccessRate", nPoints, "results.eve.packetDiagnostics");
end

wardenEbN0dB = nan(nPoints, 1);
if isfield(results, "covert") && isfield(results.covert, "warden")
    if ~isfield(results.linkBudget, "warden")
        error("export_thesis_tables:MissingWardenBudget", ...
            "results.linkBudget.warden is required when results.covert.warden is present.");
    end
    wardenBudget = local_require_budget_struct(results.linkBudget.warden, nPoints, "results.linkBudget.warden");
    wardenEbN0dB = local_require_point_vector(results.covert.warden, "wardenEbN0dB", nPoints, "results.covert.warden");
end

t = table( ...
    pointIndex, ...
    scan.snrIndex, ...
    scan.jsrIndex, ...
    bobBudget.txPowerDb, ...
    bobEbN0dB, ...
    bobJsrDb, ...
    frontEndBob, ...
    headerBob, ...
    klSignalVsNoise, ...
    klNoiseVsSignal, ...
    klSymmetric, ...
    eveEbN0dB, ...
    eveFrontEnd, ...
    eveHeader, ...
    wardenEbN0dB, ...
    'VariableNames', { ...
        'pointIndex', 'snrIndex', 'jsrIndex', 'txPowerDb', 'bobEbN0dB', 'jsrDb', ...
        'bobFrontEndSuccessRate', 'bobHeaderSuccessRate', ...
        'klSignalVsNoise', 'klNoiseVsSignal', 'klSymmetric', ...
        'eveEbN0dB', 'eveFrontEndSuccessRate', 'eveHeaderSuccessRate', ...
        'wardenEbN0dB'});
end

function t = local_build_metric_table(methods, roleName, txPowerDb, ebN0dB, jsrDb, scan, ber, rawPer, per, rawPayloadSuccessRate, payloadSuccessRate, commMetrics, compMetrics, frontEndSuccessRate, headerSuccessRate)
nMethods = numel(methods);
nPoints = numel(ebN0dB);
pointIndex = repmat((1:nPoints).', nMethods, 1);
methodIndex = repelem((1:nMethods).', nPoints, 1);
berVec = reshape(ber.', [], 1);
rawPerVec = reshape(rawPer.', [], 1);
perVec = reshape(per.', [], 1);
rawPayloadVec = reshape(rawPayloadSuccessRate.', [], 1);
payloadVec = reshape(payloadSuccessRate.', [], 1);
commMseVec = reshape(commMetrics.mse.', [], 1);
commPsnrVec = reshape(commMetrics.psnr.', [], 1);
commSsimVec = reshape(commMetrics.ssim.', [], 1);
compMseVec = reshape(compMetrics.mse.', [], 1);
compPsnrVec = reshape(compMetrics.psnr.', [], 1);
compSsimVec = reshape(compMetrics.ssim.', [], 1);

t = table( ...
    repmat(string(roleName), nMethods * nPoints, 1), ...
    methodIndex, ...
    repelem(methods, nPoints, 1), ...
    pointIndex, ...
    repmat(double(scan.snrIndex(:)), nMethods, 1), ...
    repmat(double(scan.jsrIndex(:)), nMethods, 1), ...
    repmat(double(txPowerDb(:)), nMethods, 1), ...
    repmat(double(ebN0dB(:)), nMethods, 1), ...
    repmat(double(jsrDb(:)), nMethods, 1), ...
    repmat(double(frontEndSuccessRate(:)), nMethods, 1), ...
    repmat(double(headerSuccessRate(:)), nMethods, 1), ...
    berVec, ...
    rawPerVec, ...
    perVec, ...
    rawPayloadVec, ...
    payloadVec, ...
    commMseVec, ...
    commPsnrVec, ...
    commSsimVec, ...
    compMseVec, ...
    compPsnrVec, ...
    compSsimVec, ...
    'VariableNames', { ...
        'role', 'methodIndex', 'method', 'pointIndex', 'snrIndex', 'jsrIndex', 'txPowerDb', 'ebN0dB', 'jsrDb', ...
        'frontEndSuccessRate', 'headerSuccessRate', 'ber', 'rawPer', 'per', 'rawPayloadSuccessRate', 'payloadSuccessRate', ...
        'mseComm', 'psnrComm', 'ssimComm', 'mseComp', 'psnrComp', 'ssimComp'});
end

function t = local_build_warden_table(wardenResults, bobEbN0dB, bobJsrDb, scan, nPoints)
local_require_fields(wardenResults, ["referenceLink" "wardenEbN0dB" "layers"], "results.covert.warden");

wardenEbN0dB = local_require_point_vector(wardenResults, "wardenEbN0dB", nPoints, "results.covert.warden");
layerNames = string(fieldnames(wardenResults.layers));
if isempty(layerNames)
    error("export_thesis_tables:MissingWardenLayers", ...
        "results.covert.warden.layers must not be empty.");
end

rows = table();
for i = 1:numel(layerNames)
    layerName = layerNames(i);
    layer = wardenResults.layers.(layerName);
    local_require_fields(layer, ["pd" "pfa" "pe"], "results.covert.warden.layers." + layerName);
    pd = local_require_numeric_vector(layer.pd, nPoints, "results.covert.warden.layers." + layerName + ".pd");
    pfa = local_require_numeric_vector(layer.pfa, nPoints, "results.covert.warden.layers." + layerName + ".pfa");
    pe = local_require_numeric_vector(layer.pe, nPoints, "results.covert.warden.layers." + layerName + ".pe");

    pmd = nan(nPoints, 1);
    xi = nan(nPoints, 1);
    if isfield(layer, "pmd")
        pmd = local_require_numeric_vector(layer.pmd, nPoints, "results.covert.warden.layers." + layerName + ".pmd");
    end
    if isfield(layer, "xi")
        xi = local_require_numeric_vector(layer.xi, nPoints, "results.covert.warden.layers." + layerName + ".xi");
    end

    rows = [rows; table( ... %#ok<AGROW>
        repmat(layerName, nPoints, 1), ...
        repmat(string(wardenResults.referenceLink), nPoints, 1), ...
        (1:nPoints).', ...
        double(scan.snrIndex(:)), ...
        double(scan.jsrIndex(:)), ...
        bobEbN0dB, ...
        bobJsrDb, ...
        wardenEbN0dB, ...
        pd, pfa, pmd, pe, xi, ...
        'VariableNames', { ...
            'layer', 'referenceLink', 'pointIndex', 'snrIndex', 'jsrIndex', 'bobEbN0dB', 'jsrDb', 'wardenEbN0dB', ...
            'pd', 'pfa', 'pmd', 'pe', 'xi'})];
end

t = rows;
end

function channelCfg = local_require_channel_config(channel, structName)
local_require_fields(channel, ["impulseProb" "impulseToBgRatio" "impulseWeight" "singleTone" "narrowband" "sweep" "syncImpairment" "multipath"], structName);
local_require_fields(channel.singleTone, ["enable" "weight" "freqHz" "randomPhase"], structName + ".singleTone");
local_require_fields(channel.narrowband, ["enable" "weight" "centerFreqPoints" "bandwidthFreqPoints"], structName + ".narrowband");
local_require_fields(channel.sweep, ["enable" "weight" "startHz" "stopHz" "periodSymbols" "randomPhase"], structName + ".sweep");
local_require_fields(channel.syncImpairment, ["enable" "timingOffsetSymbols" "phaseOffsetRad"], structName + ".syncImpairment");
local_require_fields(channel.multipath, ["enable" "pathDelaysSymbols" "pathGainsDb" "rayleigh"], structName + ".multipath");

pathDelaysSymbols = local_require_numeric_list(channel.multipath.pathDelaysSymbols, structName + ".multipath.pathDelaysSymbols");
pathGainsDb = local_require_numeric_list(channel.multipath.pathGainsDb, structName + ".multipath.pathGainsDb");
if numel(pathDelaysSymbols) ~= numel(pathGainsDb)
    error("export_thesis_tables:InvalidChannelConfig", ...
        "%s.multipath.pathDelaysSymbols and %s.multipath.pathGainsDb must have the same length.", ...
        structName, structName);
end

channelCfg = struct( ...
    "impulseProb", local_require_finite_scalar(channel.impulseProb, structName + ".impulseProb"), ...
    "impulseToBgRatio", local_require_finite_scalar(channel.impulseToBgRatio, structName + ".impulseToBgRatio"), ...
    "impulseWeight", local_require_finite_scalar(channel.impulseWeight, structName + ".impulseWeight"), ...
    "singleToneEnable", local_require_logical_scalar(channel.singleTone.enable, structName + ".singleTone.enable"), ...
    "singleToneWeight", local_require_finite_scalar(channel.singleTone.weight, structName + ".singleTone.weight"), ...
    "singleToneFreqHz", local_require_finite_scalar(channel.singleTone.freqHz, structName + ".singleTone.freqHz"), ...
    "singleToneRandomPhase", local_require_logical_scalar(channel.singleTone.randomPhase, structName + ".singleTone.randomPhase"), ...
    "narrowbandEnable", local_require_logical_scalar(channel.narrowband.enable, structName + ".narrowband.enable"), ...
    "narrowbandWeight", local_require_finite_scalar(channel.narrowband.weight, structName + ".narrowband.weight"), ...
    "narrowbandCenterFreqPoints", local_require_finite_scalar(channel.narrowband.centerFreqPoints, structName + ".narrowband.centerFreqPoints"), ...
    "narrowbandBandwidthFreqPoints", local_require_finite_scalar(channel.narrowband.bandwidthFreqPoints, structName + ".narrowband.bandwidthFreqPoints"), ...
    "sweepEnable", local_require_logical_scalar(channel.sweep.enable, structName + ".sweep.enable"), ...
    "sweepWeight", local_require_finite_scalar(channel.sweep.weight, structName + ".sweep.weight"), ...
    "sweepStartHz", local_require_finite_scalar(channel.sweep.startHz, structName + ".sweep.startHz"), ...
    "sweepStopHz", local_require_finite_scalar(channel.sweep.stopHz, structName + ".sweep.stopHz"), ...
    "sweepPeriodSymbols", local_require_finite_scalar(channel.sweep.periodSymbols, structName + ".sweep.periodSymbols"), ...
    "sweepRandomPhase", local_require_logical_scalar(channel.sweep.randomPhase, structName + ".sweep.randomPhase"), ...
    "syncImpairmentEnable", local_require_logical_scalar(channel.syncImpairment.enable, structName + ".syncImpairment.enable"), ...
    "syncTimingOffsetSymbols", local_require_finite_scalar(channel.syncImpairment.timingOffsetSymbols, structName + ".syncImpairment.timingOffsetSymbols"), ...
    "syncPhaseOffsetRad", local_require_finite_scalar(channel.syncImpairment.phaseOffsetRad, structName + ".syncImpairment.phaseOffsetRad"), ...
    "multipathEnable", local_require_logical_scalar(channel.multipath.enable, structName + ".multipath.enable"), ...
    "multipathPathDelaysSymbols", local_join_numeric_vector(pathDelaysSymbols), ...
    "multipathPathGainsDb", local_join_numeric_vector(pathGainsDb), ...
    "multipathRayleigh", local_require_logical_scalar(channel.multipath.rayleigh, structName + ".multipath.rayleigh"));
end

function rxCfg = local_require_rx_diversity_config(rxDiv, structName)
local_require_fields(rxDiv, ["enable" "nRx" "combineMethod"], structName);
rxCfg = struct( ...
    "enable", local_require_logical_scalar(rxDiv.enable, structName + ".enable"), ...
    "nRx", local_require_finite_scalar(rxDiv.nRx, structName + ".nRx"), ...
    "combineMethod", string(rxDiv.combineMethod));
if ~(isscalar(rxCfg.nRx) && isfinite(rxCfg.nRx) && rxCfg.nRx >= 1 && abs(rxCfg.nRx - round(rxCfg.nRx)) <= 1e-12)
    error("export_thesis_tables:InvalidRxDiversity", "%s.nRx must be a positive integer scalar.", structName);
end
rxCfg.nRx = round(rxCfg.nRx);
if strlength(rxCfg.combineMethod) == 0
    error("export_thesis_tables:InvalidRxDiversity", "%s.combineMethod must be a non-empty string scalar.", structName);
end
end

function [enabledTypes, enabledCount] = local_collect_enabled_interference_types(channelCfg)
enabledTypes = strings(1, 0);

if channelCfg.impulseWeight > 0
    if channelCfg.impulseProb <= 0
        error("export_thesis_tables:InvalidChannelConfig", ...
            "channelImpulseWeight>0 时，channelImpulseProb 必须为正。");
    end
    enabledTypes(end + 1) = "impulse"; %#ok<AGROW>
end

if channelCfg.singleToneEnable
    if channelCfg.singleToneWeight <= 0
        error("export_thesis_tables:InvalidChannelConfig", ...
            "channelSingleToneEnable=true 时，channelSingleToneWeight 必须为正。");
    end
    enabledTypes(end + 1) = "singleTone"; %#ok<AGROW>
end

if channelCfg.narrowbandEnable
    if channelCfg.narrowbandWeight <= 0
        error("export_thesis_tables:InvalidChannelConfig", ...
            "channelNarrowbandEnable=true 时，channelNarrowbandWeight 必须为正。");
    end
    enabledTypes(end + 1) = "narrowband"; %#ok<AGROW>
end

if channelCfg.sweepEnable
    if channelCfg.sweepWeight <= 0
        error("export_thesis_tables:InvalidChannelConfig", ...
            "channelSweepEnable=true 时，channelSweepWeight 必须为正。");
    end
    enabledTypes(end + 1) = "sweep"; %#ok<AGROW>
end

enabledCount = numel(enabledTypes);
if enabledCount == 0
    enabledTypes = "none";
end
end

function budget = local_require_budget_struct(budgetIn, nPoints, structName)
local_require_fields(budgetIn, ["txPowerDb" "ebN0dB" "jsrDb"], structName);
budget = struct();
budget.txPowerDb = local_require_numeric_vector(budgetIn.txPowerDb, nPoints, structName + ".txPowerDb");
budget.ebN0dB = local_require_numeric_vector(budgetIn.ebN0dB, nPoints, structName + ".ebN0dB");
budget.jsrDb = local_require_numeric_vector(budgetIn.jsrDb, nPoints, structName + ".jsrDb");
end

function scan = local_require_scan_struct(scanIn, nPoints, structName)
local_require_fields(scanIn, ["type" "ebN0dBList" "jsrDbList" "snrIndex" "jsrIndex" "nSnr" "nJsr"], structName);
scan = struct();
scan.type = string(scanIn.type);
scan.ebN0dBList = double(scanIn.ebN0dBList(:));
scan.jsrDbList = double(scanIn.jsrDbList(:));
scan.snrIndex = local_require_numeric_vector(scanIn.snrIndex, nPoints, structName + ".snrIndex");
scan.jsrIndex = local_require_numeric_vector(scanIn.jsrIndex, nPoints, structName + ".jsrIndex");
scan.nSnr = double(scanIn.nSnr);
scan.nJsr = double(scanIn.nJsr);
end

function [commMetrics, compMetrics] = local_get_image_metrics(results, nMethods, nPoints, structName)
local_require_fields(results, "imageMetrics", structName);
local_require_fields(results.imageMetrics, ["communication" "compensated"], structName + ".imageMetrics");

commMetrics = local_require_metric_struct(results.imageMetrics.communication, nMethods, nPoints, structName + ".imageMetrics.communication");
compMetrics = local_require_metric_struct(results.imageMetrics.compensated, nMethods, nPoints, structName + ".imageMetrics.compensated");
end

function metrics = local_require_metric_struct(metricsIn, nMethods, nPoints, structName)
local_require_fields(metricsIn, ["mse" "psnr" "ssim"], structName);
metrics = struct();
metrics.mse = local_require_metric_matrix(metricsIn.mse, nMethods, nPoints, structName + ".mse");
metrics.psnr = local_require_metric_matrix(metricsIn.psnr, nMethods, nPoints, structName + ".psnr");
metrics.ssim = local_require_metric_matrix(metricsIn.ssim, nMethods, nPoints, structName + ".ssim");
end

function values = local_require_metric_matrix(valuesIn, nRows, nCols, fieldName)
values = double(valuesIn);
if ~ismatrix(values) || ~isequal(size(values), [nRows nCols]) || any(~isfinite(values(:)))
    error("export_thesis_tables:InvalidMetricMatrix", ...
        "%s must be a finite %d-by-%d matrix.", fieldName, nRows, nCols);
end
end

function values = local_require_method_point_matrix(s, fieldName, nMethods, nPoints, structName)
local_require_fields(s, fieldName, structName);
values = local_require_metric_matrix(s.(fieldName), nMethods, nPoints, structName + "." + fieldName);
end

function values = local_require_point_vector(s, fieldName, nPoints, structName)
local_require_fields(s, fieldName, structName);
values = local_require_numeric_vector(s.(fieldName), nPoints, structName + "." + fieldName);
end

function values = local_require_numeric_vector(valuesIn, nPoints, fieldName)
values = double(valuesIn(:));
if numel(values) ~= nPoints || any(~isfinite(values))
    error("export_thesis_tables:InvalidNumericVector", ...
        "%s must be a finite vector with %d elements.", fieldName, nPoints);
end
end

function value = local_require_finite_scalar(valueIn, fieldName)
value = double(valueIn);
if ~isscalar(value) || ~isfinite(value)
    error("export_thesis_tables:InvalidScalar", ...
        "%s must be a finite scalar.", fieldName);
end
end

function value = local_require_logical_scalar(valueIn, fieldName)
if ~isscalar(valueIn) || ~(islogical(valueIn) || isnumeric(valueIn))
    error("export_thesis_tables:InvalidLogicalScalar", ...
        "%s must be a logical scalar.", fieldName);
end
value = logical(valueIn);
end

function values = local_require_numeric_list(valuesIn, fieldName)
values = double(valuesIn(:).');
if isempty(values) || any(~isfinite(values))
    error("export_thesis_tables:InvalidNumericList", ...
        "%s must be a nonempty finite numeric vector.", fieldName);
end
end

function local_require_fields(s, fieldNames, structName)
if nargin < 3
    structName = "struct";
end
fieldNames = string(fieldNames);
for i = 1:numel(fieldNames)
    fieldName = fieldNames(i);
    if ~isfield(s, fieldName)
        error("export_thesis_tables:MissingField", ...
            "Missing required field %s.%s.", structName, fieldName);
    end
end
end

function txt = local_join_string_vector(values)
values = string(values(:).');
txt = join(values, ",");
txt = txt(1);
end

function txt = local_join_numeric_vector(values)
values = double(values(:).');
parts = compose("%.6g", values);
txt = join(parts, ",");
txt = txt(1);
end
